# Generated by Django 2.1.7 on 2019-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('square_feet', models.IntegerField()),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-price',),
            },
        ),
    ]
