# Generated by Django 2.1.7 on 2019-03-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('square_feet', models.IntegerField()),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'ordering': ('-date', '-price'),
            },
        ),
    ]
